# Generated by Django 4.0 on 2022-01-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='crete_date',
            new_name='create_date',
        ),
    ]
