# Generated by Django 4.0 on 2022-01-08 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pybo', '0002_rename_crete_date_question_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='auther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
